// Code generated by goctl. DO NOT EDIT.
package types

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	FilePath string `json:"filePath"`
	Code     int    `json:"code"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	Code         int64  `json:"code"`
}
